export const webRouteContracts = [
  {
    source: "apps/web/app/routes/_index.tsx",
    currentPath: "/",
    nextTarget: "app/page.tsx",
  },
  {
    source: "apps/web/app/routes/auth/route.tsx",
    currentPath: "/auth",
    nextTarget: "app/auth/page.tsx",
  },
  {
    source: "apps/web/app/routes/admin/route.tsx",
    currentPath: "/admin",
    nextTarget: "app/admin/page.tsx",
  },
  {
    source: "apps/web/app/routes/admin.pos/route.tsx",
    currentPath: "/admin/pos",
    nextTarget: "app/admin/pos/page.tsx",
  },
  {
    source: "apps/web/app/routes/admin.cooker/route.tsx",
    currentPath: "/admin/cooker",
    nextTarget: "app/admin/cooker/page.tsx",
  },
  {
    source: "apps/web/app/routes/client.table.$id/route.tsx",
    currentPath: "/client/table/:id",
    nextTarget: "app/client/table/[id]/page.tsx",
  },
] as const;

export const apiRouteContracts = [
  "GET /api",
  "GET /image/:filename",
  "POST /api/auth/sign-up",
  "POST /api/auth/sign-in",
  "POST /api/auth/sign-out",
  "GET /api/auth/session",
  "GET /api/menu",
  "GET /api/table",
  "POST /api/order",
  "GET /api/order/:tableId",
  "GET /api/order/:tableId/:orderId",
  "DELETE /api/order",
  "GET /api/admin/menu",
  "GET /api/admin/menu/:menuId",
  "POST /api/admin/menu",
  "PUT /api/admin/menu",
  "DELETE /api/admin/menu",
  "POST /api/admin/menuCategory",
  "PUT /api/admin/menuCategory",
  "DELETE /api/admin/menuCategory",
  "GET /api/admin/table",
  "POST /api/admin/table",
  "PUT /api/admin/table",
  "PUT /api/admin/table/occupy",
  "PUT /api/admin/table/vacate",
  "DELETE /api/admin/table",
  "PUT /api/admin/order",
  "PUT /api/admin/order/cancel",
  "PUT /api/admin/order/complete",
  "PUT /api/admin/order/pick-up",
  "PUT /api/admin/order/refund",
  "DELETE /api/admin/order",
  "GET /api/admin/deposit",
  "POST /api/admin/deposit",
  "PUT /api/admin/deposit/confirm",
  "PUT /api/admin/deposit/ignore",
  "GET /api/admin/payout",
  "PUT /api/admin/image",
] as const;

export const migrationHotspots = [
  "createOrder",
  "removeOrder",
  "CartModal",
  "CartAddModal",
  "OrderModal",
  "OrderHistoryModal",
  "InventoryCreateModal",
  "InventoryDetailModal",
  "queryStore",
  "toast",
  "useValidateOrder",
] as const;
